### ISSUE TITLE
How to update the page

### ISSUE THREAD

**Issue by carlosperate** [mu-editor/mu-editor.github.io#1]
I was just wondering if the page was autogenerated with any template and how updates can be added. We could add a 1-line instruction about installing in the raspberry pi, in case people find this page before they find the official raspberry pi resources.

Also, it maybe nice to have a screenshot in there?

**Comment by ntoll** [comment]
I'll try to get something written over the weekend. :-)

**Comment by ntoll** [comment]
Please see https://mu.readthedocs.io/en/latest/website.html for a solution to this ticket (how to update the website).
