### ISSUE TITLE
Can we move the mu*.tar.gz files into a different directory?

### ISSUE THREAD

**Issue by carlosperate** [mu-editor/mu-editor.github.io#11]
We currently link to the GitHub Releases executables from https://github.com/mu-editor/mu/releases
The releases also packs the code in .tar.gz files, is there a reason to keep copies in this repository?

If we do need them, could we move them to a subfolder? Are there any perma-links that depend in the current location?

**Comment by ntoll** [comment]
These are not needed and could be deleted.

**Comment by ntoll** [comment]
Fixed by 076e54ccc538b1e665f3147e85fe2a688d0a388a
