### ISSUE TITLE
Check Mu/docs latest version available using GitHub API

### ISSUE THREAD

**Issue by carlosperate** [mu-editor/mu-editor.github.io#14]
Opening this issue as a reminder of https://github.com/mu-editor/mu-editor.github.io/pull/9#discussion_r112589431.

At the moment the "latest available version", used to determine if a "update warning" has to be injected in the help pages, is set by a hard-coded string.
Instead we could use the GitHub API to read the version of the latest Mu release and use that instead.

**Comment by ZanderBrown** [comment]
Before i loose it: https://api.github.com/repos/mu-editor/mu/releases/latest
