### ISSUE TITLE
Linux Download info should indicate is 64 bit only

### ISSUE THREAD

**Issue by carlosperate** [mu-editor/mu-editor.github.io#19]
As discussed in https://github.com/mu-editor/mu/issues/279

**Comment by ntoll** [comment]
+1

This could be done in two ways:

1) The filename says `amd64` somewhere in it.
2) We say something about it on the website as discussed in the linked ticket.

Alternatively, we could do:

3) Make a build for 32bit Linux. But before we know it we'll have people asking for 16bit Amiga and then 8bit Commodore 64 builds. Also, I believe this path wouldn't be conducive to @carlosperate's sanity. :-P

**Comment by ntoll** [comment]
We no longer provide Linux binaries since we're hoping to get Mu into Debian and Fedora. This issue is therefore dead.

**Comment by ZanderBrown** [comment]
Mu 0.9.13 is already in Fedora and the [gears in motion](https://apps.fedoraproject.org/datagrepper/raw?package=mu) for 1.0
