### ISSUE TITLE
Please check the "first draft" for the new design for the website

### ISSUE THREAD

**Issue by ntoll** [mu-editor/mu-editor.github.io#22]
It's in the `v1` branch and you'll need to install and run Jekyll to see it run locally.

All feedback most welcome. It's obviously bootstrap based (v3) and I've gone for simplicity. I hope you like the animated GIFs. ;-)

The work so far is in POSH (plain old semantic HTML) although the content for the tutorials and how-tos will be Markdown (and thus editable in GitHub). When this lands, I intend to kill off the help related repos since they'll be redundant. In the meantime I intend writing the tutorials and how-tos over the coming week or so.

**Comment by ZanderBrown** [comment]
Mirrored [here](https://zanderbrown.github.io/mu-editor.github.io/) for convenience (obviously quite a few broken links as it's not designed to run in a subdirectory and content hasn't been written yet)

Looking good, bootstrap makes it look a little generic but that isn't necessarily a bad thing.

Like the thanks page :-)

**Comment by ntoll** [comment]
@ZanderBrown you really should come to PyCon UK just so I can confirm you're not any of the things I claim you are... ;-)

**Comment by ntoll** [comment]
It's alive! (And this issue is therefore dead). ;-)
