### ISSUE TITLE
Suggested Page: Keyboard shortcuts

### ISSUE THREAD

**Issue by carlosperate** [mu-editor/mu-editor.github.io#30]
To have a user page to list all the available keyboard shortcuts.

@ntoll Are any of the shortcuts created by PyQt5 or Qscintilla directly? If so, do they follow OS conventions and change depending on that?

**Comment by carlosperate** [comment]
Related GH issues/features for reference: 
* https://github.com/mu-editor/mu/issues/516 - Feature request: Indentation and commenting options 
* https://github.com/mu-editor/mu/issues/323 - change - 'ctrl-D' in MU code editor window to something else
* https://github.com/mu-editor/mu/issues/169 - Copy/Paste via keys not working in REPL
* https://github.com/mu-editor/mu/issues/90 - Find and replace
* https://github.com/mu-editor/mu/issues/37#issuecomment-322537540 - Add keyboard shortcuts

**Comment by ntoll** [comment]
@carlosperate there's been a "slot" for this sort of thing for months, on this page: https://codewith.mu/en/tutorials/ It'll be filled in once beta.17 is out and I find the time to write it.

**Comment by carlosperate** [comment]
Awesome!
I knew there was something in the works, but coudn't find any specific markdown file in the repo so I thought a ticket in the repo could be a good place to collect some of the different shortcuts we need to capture in the doc.

**Comment by ntoll** [comment]
Yup, I have a draft with all the things documented (and tested against Mu).

BTW, how's the testing going on the new flash..?

**Comment by ZanderBrown** [comment]
Semi-related: I know this is an unwinnable battle but the 'start here' GIF doesn't show the new styling

**Comment by carlosperate** [comment]
> BTW, how's the testing going on the new flash..?

Looking at it now

**Comment by ntoll** [comment]
@ZanderBrown next week is "finish the damn website" week for me... ;-) Good spot. If you see anything else, please do let me know.

**Comment by tjguk** [comment]
I'll take the liberty of closing this now that @ntoll has done the tutorials, including a page on shortcuts.

**Comment by ntoll** [comment]
+1 I'm going to do "issue gardening" when I get back from holiday. ;-)
