### ISSUE TITLE
Separating help markdown from website project repository?

### ISSUE THREAD

**Issue by carlosperate** [mu-editor/mu-editor.github.io#4]
So, with the imminent update to the website to use github pages with jekyll we'll have the advantage of being able to have simple markdown files for the documentation.
As far as I can see they will live in a folder as shown in:
https://github.com/dannystaple/mu-editor.github.io/tree/master/help

The HTML output is not saved into the repository, just the project files and content, and so the static site is automatically generated by github on commits (not sure where it goes, but they are served on http://mu-editor.github.io). As we want to maintain old versions of the documentation we will end up keeping old versions of the markdown files on version folders as shown in the first link.

This is probably a bit confusing for newcomers that might want to contribute to the docs, especially since the repository itself will be filled with scary files.

My suggestion would be to have a different repo just for the markdown docs, where the master is always the latest, and we label the documentation for individual Mu releases as git-tags (with or without github releases) on this new repository. Then, for the mu-editor/mu-editor.github.io repo we can have a git submodule for each version pointing to their respective commit.

Btw, I had a quick and looks like this feature is supported by GitHub pages: https://help.github.com/articles/using-submodules-with-pages/

Thoughts?

**Comment by dannystaple** [comment]
That is a neat idea - so in the help git repo - only the md files, making it nice and clear. So a repo like mu-editor/help? And initially - copy over the files from the help subdirectory, and drop them in there, then reference it as the submodule. It also means that help images should stay in the help repo. One thing worth considering - we may need to prod or touch a file in the main repo to get it to regenerate from the submodule.

**Comment by carlosperate** [comment]
>  It also means that help images should stay in the help repo.

Could be problematic for the page generation? since the images used could change with the rest of the documentation, is there a way for each subdirectory within `help` could have it's own image folder? so could we have `help/0.9.11/images`?

>  One thing worth considering - we may need to prod or touch a file in the main repo to get it to regenerate from the submodule.

Well, I'm assuming that by adding a new submodule or changing the commit hash for any existing submodule would be enough to trigger a page build, as there will be a new commit added to the repository.

**Comment by dannystaple** [comment]
I see no reason why not - images can be anywhere in the structure - they
are just static files. It's only that "_posts" where things get a bit
different.

I think it's worth experimenting with the submodule to see if it works. I'm
happy to play with this idea - assign it to me?

**Comment by carlosperate** [comment]
That'd be great, thanks @dannystaple!

**Comment by carlosperate** [comment]
Implemented in https://github.com/mu-editor/mu-editor.github.io/pull/9.
