### ISSUE TITLE
Note on the authors page to point people for help

### ISSUE THREAD

**Issue by tjguk** [mu-editor/mu-editor.github.io#56]
We just had someone email a scattering of developers picked up from the authors page on the website. I've pointed the user to the Gitter channel, and they referred me to the authors page where they'd picked up various emails.

Suggest we want to add a line sayIng: don't email these people directly for help. (Maybe even remove the email addresses, which don't need strictly need to be there the purposes of aknowledgement)

**Comment by prcutler** [comment]
Hi, 

I know this is an older issue, but are you referring to the AUTHORS file in the Mu repo here?  https://github.com/mu-editor/mu/blob/master/AUTHORS.rst

If so, I'd be happy to submit a PR to remove the email addresses.  

I did not see an AUTHORS file in the website repo.
