### ISSUE TITLE
404 page is always in Spanish

### ISSUE THREAD

**Issue by tim-mccurrach** [mu-editor/mu-editor.github.io#58]
Navigating to any of the following pages (for me) takes me to the Spanish version of the 404 page. 
 - https://codewith.mu/non-existing-page
 - https://codewith.mu/en/non-existing-page
 - https://codewith.mu/fr/non-existing-page

(This is on a mac in the UK with all language preferences set to English). 

It looks like the issue is here: https://github.com/mu-editor/mu-editor.github.io/commit/3a5557ccdda9db5c81f667dec2df0b7842b5da5a

**Comment by carlosperate** [comment]
Thanks @tim-mccurrach, I just noticed this as well!

@ntoll the page was edited as part of https://github.com/mu-editor/mu-editor.github.io/pull/57
I guess it'll be quite hard to localise that page (maybe we can detect something with a bit of js), but in the meantime we should revert the English version.

**Comment by ntoll** [comment]
Fixed by 4d43c06
