### ISSUE TITLE
Can we delete these files from the repository?

### ISSUE THREAD

**Issue by carlosperate** [mu-editor/mu-editor.github.io#6]
Would it be safe to remove the files within `_drafts` directory and the `_posts/core-samples/` folder with the `2011-12-29-jekyll-introduction.md` file?
I'm not familiar at all with Jekyll or ruby, but these look like example "posts" from the project creation?

**Comment by dannystaple** [comment]
yes - they can safely be removed. we should consider if we want a placeholder file in _posts since git won't keep empty folders - but since it's the same structure as every other jekyll site it wouldn't be hard to recreate if blog posts were something we wanted.

**Comment by carlosperate** [comment]
Yeah, that's a good point with the empty folders. What I've done in the past is to have a readme.md in the directory with some short explanation, but I assume that would create a post named "readme"? Could we have a txt file or something like that instead without a post being created?

For the draft folders I assume it is used as a "staging" folder and does not generate and publish any pages from the markdown files there, would that be correct? If that's the case then maybe we could a "template.md" file to indicate and document how to create these files (the header and stuff like that).

**Comment by dannystaple** [comment]
Drafts is indeed staging - it is shown when you do a local `jekyll serve` but not output in a `jekyll build`. It should not show up in the generated output.
I think an md without the header is now included as a post - so that would work. Assign this to me, I'll play with that - drop in a template in drafts, and a help file in _posts to say how to get it start generating blog posts.

**Comment by carlosperate** [comment]
Awesome, I'll assign the issue to you :)

**Comment by ntoll** [comment]
Fixed with merge of #7

**Comment by ntoll** [comment]
THANKS! :-)
