### ISSUE TITLE
Highlight the Operating System download based on the user agent

### ISSUE THREAD

**Issue by tonybaloney** [mu-editor/mu-editor.github.io#68]
It would be helpful for users to have the Operating System highlighted based on which OS they are using:

![image](https://user-images.githubusercontent.com/1532417/179358695-328ce9d0-a1b2-4d84-88c5-0e3c8e776d0e.png)

**Comment by carlosperate** [comment]
Done in PR https://github.com/mu-editor/mu-editor.github.io/pull/69 and https://github.com/mu-editor/mu-editor.github.io/pull/73, thanks @tonybaloney!
